name = "worker-telegram-ping"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-23"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
